/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author macbook
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tenNv = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jpTrangChu2 = new javax.swing.JPanel();
        jlTrangChu2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jpTrangChu = new javax.swing.JPanel();
        jlTrangChu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpTrangChu3 = new javax.swing.JPanel();
        jlTrangChu3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpTrangChu4 = new javax.swing.JPanel();
        jlTrangChu4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpTrangChu5 = new javax.swing.JPanel();
        jlTrangChu5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jpTrangChu6 = new javax.swing.JPanel();
        jlTrangChu6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jpTrangChu7 = new javax.swing.JPanel();
        jlTrangChu7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jpTrangChu8 = new javax.swing.JPanel();
        jlTrangChu8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trang Chủ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 6, 238, 62));
        jPanel2.add(tenNv, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 21, 119, 35));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_rounded_left_40px.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(944, 0, 68, 68));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minus_math_40px.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1024, 6, 73, 62));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/multiply_40px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1103, 0, 63, 68));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 70));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 74, 920, 640));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 74, -1, 748));

        jpTrangChu2.setBackground(new java.awt.Color(30, 30, 30));
        jpTrangChu2.setPreferredSize(new java.awt.Dimension(225, 88));
        jpTrangChu2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTrangChu2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jlTrangChu2.setForeground(new java.awt.Color(153, 153, 153));
        jlTrangChu2.setText("Trang Chủ");
        jlTrangChu2.setPreferredSize(new java.awt.Dimension(160, 24));
        jpTrangChu2.add(jlTrangChu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, -1, 203, 80));

        jLabel7.setBackground(new java.awt.Color(30, 30, 30));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trang chu.png"))); // NOI18N
        jpTrangChu2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 3, 44, 60));

        jPanel1.add(jpTrangChu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 259, 80));

        jpTrangChu.setBackground(new java.awt.Color(30, 30, 30));
        jpTrangChu.setPreferredSize(new java.awt.Dimension(225, 88));
        jpTrangChu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTrangChu.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jlTrangChu.setForeground(new java.awt.Color(153, 153, 153));
        jlTrangChu.setText("Nhập Hàng");
        jlTrangChu.setPreferredSize(new java.awt.Dimension(160, 24));
        jpTrangChu.add(jlTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 200, 80));

        jLabel5.setBackground(new java.awt.Color(30, 30, 30));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/news.png"))); // NOI18N
        jpTrangChu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 44, 57));

        jPanel1.add(jpTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 259, 80));

        jpTrangChu3.setBackground(new java.awt.Color(30, 30, 30));
        jpTrangChu3.setPreferredSize(new java.awt.Dimension(225, 88));
        jpTrangChu3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTrangChu3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jlTrangChu3.setForeground(new java.awt.Color(153, 153, 153));
        jlTrangChu3.setText("Giảm Giá");
        jlTrangChu3.setPreferredSize(new java.awt.Dimension(160, 24));
        jpTrangChu3.add(jlTrangChu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 0, 200, 80));

        jLabel8.setBackground(new java.awt.Color(30, 30, 30));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shop_42px.png"))); // NOI18N
        jpTrangChu3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 44, 57));

        jPanel1.add(jpTrangChu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 259, 80));

        jpTrangChu4.setBackground(new java.awt.Color(30, 30, 30));
        jpTrangChu4.setPreferredSize(new java.awt.Dimension(225, 88));
        jpTrangChu4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTrangChu4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jlTrangChu4.setForeground(new java.awt.Color(153, 153, 153));
        jlTrangChu4.setText("Kho");
        jlTrangChu4.setPreferredSize(new java.awt.Dimension(160, 24));
        jpTrangChu4.add(jlTrangChu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 0, 200, 80));

        jLabel9.setBackground(new java.awt.Color(30, 30, 30));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/truck_42px.png"))); // NOI18N
        jpTrangChu4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 44, 57));

        jPanel1.add(jpTrangChu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 259, 80));

        jpTrangChu5.setBackground(new java.awt.Color(30, 30, 30));
        jpTrangChu5.setPreferredSize(new java.awt.Dimension(225, 88));
        jpTrangChu5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTrangChu5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jlTrangChu5.setForeground(new java.awt.Color(153, 153, 153));
        jlTrangChu5.setText("Hoá Đơn");
        jlTrangChu5.setPreferredSize(new java.awt.Dimension(160, 24));
        jpTrangChu5.add(jlTrangChu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 0, 200, 80));

        jLabel10.setBackground(new java.awt.Color(30, 30, 30));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save_as_42px.png"))); // NOI18N
        jpTrangChu5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 44, 57));

        jPanel1.add(jpTrangChu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 259, 80));

        jpTrangChu6.setBackground(new java.awt.Color(30, 30, 30));
        jpTrangChu6.setPreferredSize(new java.awt.Dimension(225, 88));
        jpTrangChu6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTrangChu6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jlTrangChu6.setForeground(new java.awt.Color(153, 153, 153));
        jlTrangChu6.setText("Sản Phẩm");
        jlTrangChu6.setPreferredSize(new java.awt.Dimension(160, 24));
        jpTrangChu6.add(jlTrangChu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 0, 200, 80));

        jLabel11.setBackground(new java.awt.Color(30, 30, 30));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_shelf_42px.png"))); // NOI18N
        jpTrangChu6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 44, 57));

        jPanel1.add(jpTrangChu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 259, 80));

        jpTrangChu7.setBackground(new java.awt.Color(30, 30, 30));
        jpTrangChu7.setPreferredSize(new java.awt.Dimension(225, 88));
        jpTrangChu7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTrangChu7.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jlTrangChu7.setForeground(new java.awt.Color(153, 153, 153));
        jlTrangChu7.setText("Tài Khoản");
        jlTrangChu7.setPreferredSize(new java.awt.Dimension(160, 24));
        jpTrangChu7.add(jlTrangChu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 0, 200, 80));

        jLabel12.setBackground(new java.awt.Color(30, 30, 30));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_account_skin_type_7_42px.png"))); // NOI18N
        jpTrangChu7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 44, 57));

        jPanel1.add(jpTrangChu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 259, 80));

        jpTrangChu8.setBackground(new java.awt.Color(30, 30, 30));
        jpTrangChu8.setPreferredSize(new java.awt.Dimension(225, 88));
        jpTrangChu8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTrangChu8.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jlTrangChu8.setForeground(new java.awt.Color(153, 153, 153));
        jlTrangChu8.setText("Của Hàng");
        jlTrangChu8.setPreferredSize(new java.awt.Dimension(160, 24));
        jpTrangChu8.add(jlTrangChu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 0, 200, 80));

        jLabel13.setBackground(new java.awt.Color(30, 30, 30));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shop_42px.png"))); // NOI18N
        jpTrangChu8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 44, 57));

        jPanel1.add(jpTrangChu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 259, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlTrangChu;
    private javax.swing.JLabel jlTrangChu2;
    private javax.swing.JLabel jlTrangChu3;
    private javax.swing.JLabel jlTrangChu4;
    private javax.swing.JLabel jlTrangChu5;
    private javax.swing.JLabel jlTrangChu6;
    private javax.swing.JLabel jlTrangChu7;
    private javax.swing.JLabel jlTrangChu8;
    private javax.swing.JPanel jpTrangChu;
    private javax.swing.JPanel jpTrangChu2;
    private javax.swing.JPanel jpTrangChu3;
    private javax.swing.JPanel jpTrangChu4;
    private javax.swing.JPanel jpTrangChu5;
    private javax.swing.JPanel jpTrangChu6;
    private javax.swing.JPanel jpTrangChu7;
    private javax.swing.JPanel jpTrangChu8;
    private javax.swing.JLabel tenNv;
    // End of variables declaration//GEN-END:variables
}
